version: '3'
services:
  postgres:
    image: postgres:10.6
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'pg-user'
      POSTGRES_PASSWORD: 'top-secret'
      POSTGRES_DB: 'groupy'